fix: invalid path in update_dir param
h3xp/RickDangerousUpdate pull request #85
Opened 2022-12-01 21:08 UTC by holly79

If update_dir is an invalid path, the dialog goes back to the main dialog. Now the update_dir is set to / if it is an invalid path

2022-12-04 12:01 UTC, mrludo001 commented
In other places in the code a function get_valid_path_portion() is used to walk back up the path to what might be valid.  Have you considered if this would be appropriate here ?

2022-12-04 14:14 UTC, WolfRevo requested changes
Line 2045
`if not os.path.isdir(update_dir) and not os.path.isfile(update_dir):`
I would also suggest to change this to:
`update_dir = get_valid_path_portion(update_dir)`
With that you can remove lines 2046 to 2050 completely and unchange lines 2049/2050 (or 2052/2053 ... the intendation of the `code == d.CANCEL` stuff)

2022-12-04 16:54 UTC, holly79 commented
good idea, I use get_valid_path_portion now. But the d.Cancel and d.OK stuff must be on the same indent as get_valid_path_portion.

2022-12-04 17:05 UTC, holly79 commented
i revert the commit after testing, becaus if I use get_valid_path_portion I got back only the parent  if the path valid 

e.g. /home/pi -> /home/

I think, this is not want we want, isn't it.

2022-12-04 18:12 UTC, WolfRevo commented
I would also encourage you to use the get_valid_path_portion() 

> 

If I remember correctly from checking the `get_valid_path_portion()` function this is indeed intended behaviour as if you correctly want to adress linux folders they end with "/" so `/home/pi` needs to be `/home/pi/` instead because `/home/pi` would normally be the file `pi` in directory `/home/`. You can see this in the dialog where you choose your manual update path as well: if you just manully type in the directory in the last line it won't show you the content for `/home/pi` on the right side but as soon as you add the `/` it will show you the content on the right side. Please let me know if this is bullshit and your test does always only return the parent 😊

2022-12-04 18:51 UTC, holly79 commented
when I tested whether the path ends with a trailing slash or not, I only got back the parent directory. So I fixed get_valid_path_portion() as well and use get_valid_path_portion in downloaded_update_question_dialog now

2022-12-04 21:35 UTC, h3xp commented
@holly79 would you be interested in joining the matrix chat where we talk about everything concerning the development of this repo?

2022-12-05 12:18 UTC, holly79 commented
> @holly79 would you be interested in joining the matrix chat where we talk about everything concerning the development of this repo?

yes i can

2022-12-05 12:21 UTC, h3xp commented
> > @holly79 would you be interested in joining the matrix chat where we talk about everything concerning the development of this repo?
> 
> yes i can

https://matrix.to/#/!xmbcEVKPuJYmFBGYBi:matrix.hexp.space?via=matrix.hexp.space&via=matrix.org&via=matrix.wolfrevo.duckdns.org

2022-12-05 13:19 UTC, holly79 commented
hm...got this error

MatrixError: [403] You do not belong to any of the required rooms/spaces to join this room. (https://matrix-client.matrix.org/_matrix/client/r0/join/!xmbcEVKPuJYmFBGYBi%3Amatrix.hexp.space?server_name=matrix.hexp.space&server_name=matrix.org&server_name=matrix.wolfrevo.duckdns.org)

2022-12-05 13:26 UTC, WolfRevo commented
You first need to have (e.g. to create) a Matrix user account (you can create one on matrix.org for instance but it works with any matrix-federated server which allows user creation: https://joinmatrix.org/servers/). With that account you can join our matrix-server and channels with the link above using your favorite matrix client (element for most of the users).

2022-12-05 13:28 UTC, h3xp commented
or just hit me up on one of my linked socials or on discord, we will sort that out there instead of in the PR 😆

2022-12-05 14:19 UTC, WolfRevo approved these changes

2022-12-05 14:20 UTC, merged